# Generated by Django 6.0.3 on 2026-03-13 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={},
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='target_date',
        ),
        migrations.AddField(
            model_name='subtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='real_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
