# Generated by Django 6.0.3 on 2026-04-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtasks', '0002_alter_subtask_options_remove_subtask_target_date_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='subtask',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
