# Generated by Django 6.0.3 on 2026-04-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtasks', '0003_subtask_status_subtask_target_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('postponed', 'Pospuesta')], default='pending', max_length=20),
        ),
    ]
