# Generated by Django 6.0.3 on 2026-04-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
