# Generated by Django 4.2.9 on 2026-05-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tag',
            field=models.CharField(choices=[('tarea', 'Tarea'), ('examen', 'Examen'), ('proyecto', 'Proyecto'), ('lectura', 'Lectura')], default='tarea', max_length=20),
        ),
    ]
